### ISSUE TITLE
jeecg部署报错 [mysql-cj-abandoned-connection-cleanup] org.apache.catalina.loader.WebappClassLoader.checkStateForREsourceLoading

### ISSUE THREAD

**Issue by WuybGitHub** [jeecgboot/jeecg#81]
[mysql-cj-abandoned-connection-cleanup] org.apache.catalina.loader.WebappClassLoader.checkStateForREsourceLoading Illegal access: this web application instance has been stopped already. Could not load [] 
[systemBaseCache.data] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForREsourceLoading Illegal access: this web application
has been stopped already. Could not load [net.sf.ehcache.store.compoud.CompoundStore$KeySet].
![微信图片_20211210101441](https://user-images.githubusercontent.com/87416943/145514104-87d92b2d-d70e-405e-b07b-bcf51c08d338.jpg)

**Comment by WuybGitHub** [comment]
![Uploading 微信图片_20211210101623.jpg…]()

**Comment by xianyanzhixi** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
